// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int countBig = 0;
		int countSmall = 0;
		for (int number = 1; number <= n; number++) {
        double x = Math.random();
		if (x < 0.5) {
			countSmall++;
		} else {
			countBig++;
		}
		}
		double ratio = 0;
		if (countBig == 0 || countSmall == 0){
			System.out.println("> 0.5:  " + countSmall + " times");
			System.out.println("<= 0.5: " + countBig + " times");
		} else {
			if (countSmall > countBig) {
				ratio = ((double) countBig / countSmall);
			} else {
				ratio = ((double) countSmall / countBig);
			}
				System.out.println("> 0.5:  " + countSmall + " times");
				System.out.println("<= 0.5: " + countBig + " times");
				System.out.println("Ratio:  " + ratio);

			} 
			}
		}
		 // Replace this comment with your code
	

